# <center>Project Euler</center>

## Table of contents:
* [1. Multiples of 3 and 5](#1)
* [2. Even Fibonacci numbers](#2)
* [3. Largest prime factor](#3)
* [4. Largest palindrome product](#4)
* [5. Smallest multiple](#5)
* [6. Sum square difference](#6)
* [7. 10001st prime](#7)
* [8. Largest product in a series](#8)
* [9. Special Pythagorean triplet](#9)
* [10. Summation of primes](#10)
* [11. Largest product in a grid](#11)
* [12. Highly divisible triangular number](#12)
* [13. Large sum](#13)
* [14. Longest Collatz sequence](#14)
* [15. Lattice paths](#15)
* [16. Power digit sum](#16)
* [17. Number letter counts](#17)
* [18. Maximum path sum I](#18)
* [19. Counting Sundays](#19)
* [20. Factorial digit sum](#20)
* [21. Amicable numbers](#21)
* [22. Names scores](#22)
* [23. Non-abundant sums](#23)
* [24. Lexicographic permutations](#24)
* [25. 1000-digit Fibonacci number](#25)
* [26. Reciprocal cycles](#26)
* [27. Quadratic primes](#27)
* [28. Number spiral diagonals](#28)
* [29. Distinct powers](#29)
* [30. Digit fifth powers](#30)
* [31. Coin sums](#31)
* [32. Pandigital products](#32)
* [33. Digit cancelling fractions](#33)
* [34. Digit factorials](#34)
* [35. Circular primes](#35)

<a id='1'></a>
## 1. Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [13]:
def problem_1(n):
    numbers = 0
    for i in range(n):
        if i % 3 == 0 or i % 5 == 0:
            numbers += i
    return numbers

In [14]:
problem_1(1000)

233168

<a id='2'></a>
## 2. Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...$$

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [3]:
def problem_2(lim):
    fibs = [1, 2]
    fib = 2
    n = 3
    sum = 2
    while fib < lim:
        fib = fibs[n - 3] + fibs[n - 2]
        fibs.append(fib)
        if fib % 2 == 0:
             sum += fib
        n += 1
    return sum

In [4]:
problem_2(4e6)

4613732

<a id='3'></a>
## 3. Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143?

In [30]:
def problem_3(num):
    max_prime = 1
    if num % 2 == 0:
        max_prime = 2
        num /= 2
    for i in range(3, round(num**0.5) + 1, 2):
        if num % i == 0:
            max_prime = max(max_prime, i)
            num /= i
    return max_prime

In [31]:
problem_3(600851475143)

6857

<a id='4'></a>
## 4. Largest palindrome product

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 

$$9009 = 91 \cdot 99$$

Find the largest palindrome made from the product of two 3-digit numbers.

In [28]:
def problem_4(digit):
    palindrome = 0
    for i in range(1, 10**digit):
        for j in range(1, 10**digit):
            n = i * j
            if str(n) == str(n)[::-1]:
                palindrome = max(n, palindrome)
    return palindrome

In [29]:
problem_4(3)

906609

<a id='5'></a>
## 5. Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [25]:
def problem_5(lim):
    num = 0
    not_div = True
    while not_div:
        num += 1
        for i in range(2, lim + 1):
            not_div = num % i != 0
            if not_div:
                break
    return num

In [26]:
problem_5(20)

232792560

<a id='6'></a>
## 6. Sum square difference

The sum of the squares of the first ten natural numbers is,

$${1^2} + {2^2} ... + {10^2} = 385$$

The square of the sum of the first ten natural numbers is,

$${(1 + 2 + ... + 10)^2} = {55^2} = 3025$$

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 

$$3025 âˆ’ 385 = 2640$$

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [22]:
def problem_6(lim):
    sum_squares = square_sums = diff = 0
    for i in range(1, lim + 1):
        sum_squares += i**2
        square_sums += i
    square_sums = square_sums**2
    diff = square_sums - sum_squares
    return diff

In [23]:
problem_6(100)

25164150

<a id='7'></a>
## 7. 10001st prime

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

In [7]:
def problem_7(lim):
    n = 1
    while lim > 0:   
        n += 1
        if all(n % i for i in range(2, int(round(n**0.5 + 1)))):
            lim -= 1
    return n

In [20]:
problem_7(10001)

104743

<a id='8'></a>
## 8. Largest product in a series

The four adjacent digits in the 1000-digit number that have the greatest product are 

$$9 \cdot 9 \cdot 8 \cdot 9 = 5832$$

	73167176531330624919225119674426574742355349194934
	96983520312774506326239578318016984801869478851843
	85861560789112949495459501737958331952853208805511
	12540698747158523863050715693290963295227443043557
	66896648950445244523161731856403098711121722383113
	62229893423380308135336276614282806444486645238749
	30358907296290491560440772390713810515859307960866
	70172427121883998797908792274921901699720888093776
	65727333001053367881220235421809751254540594752243
	52584907711670556013604839586446706324415722155397
	53697817977846174064955149290862569321978468622482
	83972241375657056057490261407972968652414535100474
	82166370484403199890008895243450658541227588666881
	16427171479924442928230863465674813919123162824586
	17866458359124566529476545682848912883142607690042
	24219022671055626321111109370544217506941658960408
	07198403850962455444362981230987879927244284909188
	84580156166097919133875499200524063689912560717606
	05886116467109405077541002256983155200055935729725
	71636269561882670428252483600823257530420752963450
    
Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [1]:
def problem_8(lim):
    number = '''73167176531330624919225119674426574742355349194934
	96983520312774506326239578318016984801869478851843
	85861560789112949495459501737958331952853208805511
	12540698747158523863050715693290963295227443043557
	66896648950445244523161731856403098711121722383113
	62229893423380308135336276614282806444486645238749
	30358907296290491560440772390713810515859307960866
	70172427121883998797908792274921901699720888093776
	65727333001053367881220235421809751254540594752243
	52584907711670556013604839586446706324415722155397
	53697817977846174064955149290862569321978468622482
	83972241375657056057490261407972968652414535100474
	82166370484403199890008895243450658541227588666881
	16427171479924442928230863465674813919123162824586
	17866458359124566529476545682848912883142607690042
	24219022671055626321111109370544217506941658960408
	07198403850962455444362981230987879927244284909188
	84580156166097919133875499200524063689912560717606
	05886116467109405077541002256983155200055935729725
	71636269561882670428252483600823257530420752963450'''.replace('\n', '').replace('\t', '')
    
    max_prod = 0
    for i in range(0, len(number) - lim):
        prod = 1
        for j in range(i, i + lim):
            prod *= int(number[j])
        max_prod = max(prod, max_prod)
    return max_prod

In [19]:
problem_8(13)

23514624000

<a id='9'></a>
## 9. Special Pythagorean triplet

A Pythagorean triplet is a set of three natural numbers, $a < b < c$, for which,

$${a^2} + {b^2} = {c^2}$$

For example, $${3^2} + {4^2} = 9 + 16 = 25 = {5^2}$$

There exists exactly one Pythagorean triplet for which $a + b + c = 1000$.

Find the product abc.

In [3]:
def problem_9(lim):
    product = 6
    for a in range(1, lim // 3):
        for b in range(a + 1, lim // 2):
            for c in range(b + 1, lim - 2):
                if (a + b + c) != lim or (a**2 + b**2) != c**2:
                    continue
                product = max(a * b * c, product)
    return product

In [18]:
problem_9(1000)

31875000

<a id='10'></a>
## 10. Summation of primes

The sum of the primes below 10 is 

$$2 + 3 + 5 + 7 = 17$$

Find the sum of all the primes below two million.

In [8]:
def problem_10(lim):
    n = 1
    add = 0
    while True:   
        if n == lim:
            break
        n += 1
        if all(n % i for i in range(2, int(round(n**0.5 + 1)))):
            add += n
    return add

In [17]:
problem_10(2000000)

142913828922

<a id='11'></a>
## 11. Largest product in a grid

In the 20x20 grid below, four numbers along a diagonal line have been marked in red.

    08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
	49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
	81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
	52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
	22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
	24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
	32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
	67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
	24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
	21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
	78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
	16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
	86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
	19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
	04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
	88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
	04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
	20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
	20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
	01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
    
The product of these numbers is 

$$26 \cdot 63 \cdot 78 \cdot 14 = 1788696$$

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20x20 grid?

In [12]:
def problem_11(size):
    grid = '''08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
	49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
	81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
	52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
	22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
	24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
	32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
	67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
	24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
	21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
	78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
	16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
	86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
	19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
	04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
	88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
	04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
	20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
	20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
	01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48'''
    
    nums_list = [list(map(int, row.split())) for row in grid.replace('\t', ' ').split('\n')]
    max_prod = 1
    
    for i in range(20):
        for j in range(20):
            for dx in range(-1, 2):
                for dy in range(-1, 2):
                    x, y = i + dx * (size - 1), j + dy * (size - 1)
                    if 0 <= x <= 19 and 0 <= y <= 19 and (dx != 0 or dy != 0):
                        prod = 1
                        for k in range(size):
                            x, y = i + dx * k, j + dy * k
                            prod *= nums_list[x][y]
                            max_prod = max(max_prod, prod)
    return max_prod

In [16]:
problem_11(4)

70600674

<a id='12'></a>
## 12. Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be:

$$1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$$

The first ten terms would be:

$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...$$

Let us list the factors of the first seven triangle numbers:
* $1: 1$
* $3: 1,3$
* $6: 1,2,3,6$
* $10: 1,2,5,10$
* $15: 1,3,5,15$
* $21: 1,3,7,21$
* $28: 1,2,4,7,14,28$

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

In [13]:
def problem_12(lim):
    n = 1
    triang = 1
    divisors = 0
    while divisors < lim:
        n += 1
        triang += n
        divisors = 0
        for i in range(1, int(triang**0.5) + 1):
            if triang % i == 0:
                if triang / i == i:
                    divisors += 1
                else:
                    divisors += 2
    return triang

In [15]:
problem_12(500)

76576500

<a id='13'></a>
## 13. Large sum

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

	37107287533902102798797998220837590246510135740250
	46376937677490009712648124896970078050417018260538
	74324986199524741059474233309513058123726617309629
	91942213363574161572522430563301811072406154908250
	23067588207539346171171980310421047513778063246676
	89261670696623633820136378418383684178734361726757
	28112879812849979408065481931592621691275889832738
	44274228917432520321923589422876796487670272189318
	47451445736001306439091167216856844588711603153276
	70386486105843025439939619828917593665686757934951
	62176457141856560629502157223196586755079324193331
	64906352462741904929101432445813822663347944758178
	92575867718337217661963751590579239728245598838407
	58203565325359399008402633568948830189458628227828
	80181199384826282014278194139940567587151170094390
	35398664372827112653829987240784473053190104293586
	86515506006295864861532075273371959191420517255829
	71693888707715466499115593487603532921714970056938
	54370070576826684624621495650076471787294438377604
	53282654108756828443191190634694037855217779295145
	36123272525000296071075082563815656710885258350721
	45876576172410976447339110607218265236877223636045
	17423706905851860660448207621209813287860733969412
	81142660418086830619328460811191061556940512689692
	51934325451728388641918047049293215058642563049483
	62467221648435076201727918039944693004732956340691
	15732444386908125794514089057706229429197107928209
	55037687525678773091862540744969844508330393682126
	18336384825330154686196124348767681297534375946515
	80386287592878490201521685554828717201219257766954
	78182833757993103614740356856449095527097864797581
	16726320100436897842553539920931837441497806860984
	48403098129077791799088218795327364475675590848030
	87086987551392711854517078544161852424320693150332
	59959406895756536782107074926966537676326235447210
	69793950679652694742597709739166693763042633987085
	41052684708299085211399427365734116182760315001271
	65378607361501080857009149939512557028198746004375
	35829035317434717326932123578154982629742552737307
	94953759765105305946966067683156574377167401875275
	88902802571733229619176668713819931811048770190271
	25267680276078003013678680992525463401061632866526
	36270218540497705585629946580636237993140746255962
	24074486908231174977792365466257246923322810917141
	91430288197103288597806669760892938638285025333403
	34413065578016127815921815005561868836468420090470
	23053081172816430487623791969842487255036638784583
	11487696932154902810424020138335124462181441773470
	63783299490636259666498587618221225225512486764533
	67720186971698544312419572409913959008952310058822
	95548255300263520781532296796249481641953868218774
	76085327132285723110424803456124867697064507995236
	37774242535411291684276865538926205024910326572967
	23701913275725675285653248258265463092207058596522
	29798860272258331913126375147341994889534765745501
	18495701454879288984856827726077713721403798879715
	38298203783031473527721580348144513491373226651381
	34829543829199918180278916522431027392251122869539
	40957953066405232632538044100059654939159879593635
	29746152185502371307642255121183693803580388584903
	41698116222072977186158236678424689157993532961922
	62467957194401269043877107275048102390895523597457
	23189706772547915061505504953922979530901129967519
	86188088225875314529584099251203829009407770775672
	11306739708304724483816533873502340845647058077308
	82959174767140363198008187129011875491310547126581
	97623331044818386269515456334926366572897563400500
	42846280183517070527831839425882145521227251250327
	55121603546981200581762165212827652751691296897789
	32238195734329339946437501907836945765883352399886
	75506164965184775180738168837861091527357929701337
	62177842752192623401942399639168044983993173312731
	32924185707147349566916674687634660915035914677504
	99518671430235219628894890102423325116913619626622
	73267460800591547471830798392868535206946944540724
	76841822524674417161514036427982273348055556214818
	97142617910342598647204516893989422179826088076852
	87783646182799346313767754307809363333018982642090
	10848802521674670883215120185883543223812876952786
	71329612474782464538636993009049310363619763878039
	62184073572399794223406235393808339651327408011116
	66627891981488087797941876876144230030984490851411
	60661826293682836764744779239180335110989069790714
	85786944089552990653640447425576083659976645795096
	66024396409905389607120198219976047599490197230297
	64913982680032973156037120041377903785566085089252
	16730939319872750275468906903707539413042652315011
	94809377245048795150954100921645863754710598436791
	78639167021187492431995700641917969777599028300699
	15368713711936614952811305876380278410754449733078
	40789923115535562561142322423255033685442488917353
	44889911501440648020369068063960672322193204149535
	41503128880339536053299340368006977710650566631954
	81234880673210146739058568557934581403627822703280
	82616570773948327592232845941706525094512325230608
	22918802058777319719839450180888072429661980811197
	77158542502016545090413245809786882778948721859617
	72107838435069186155435662884062257473692284509516
	20849603980134001723930671666823555245252804609722
	53503534226472524250874054075591789781264330331690

In [32]:
def problem_13(size):
    grid = '''37107287533902102798797998220837590246510135740250
	46376937677490009712648124896970078050417018260538
	74324986199524741059474233309513058123726617309629
	91942213363574161572522430563301811072406154908250
	23067588207539346171171980310421047513778063246676
	89261670696623633820136378418383684178734361726757
	28112879812849979408065481931592621691275889832738
	44274228917432520321923589422876796487670272189318
	47451445736001306439091167216856844588711603153276
	70386486105843025439939619828917593665686757934951
	62176457141856560629502157223196586755079324193331
	64906352462741904929101432445813822663347944758178
	92575867718337217661963751590579239728245598838407
	58203565325359399008402633568948830189458628227828
	80181199384826282014278194139940567587151170094390
	35398664372827112653829987240784473053190104293586
	86515506006295864861532075273371959191420517255829
	71693888707715466499115593487603532921714970056938
	54370070576826684624621495650076471787294438377604
	53282654108756828443191190634694037855217779295145
	36123272525000296071075082563815656710885258350721
	45876576172410976447339110607218265236877223636045
	17423706905851860660448207621209813287860733969412
	81142660418086830619328460811191061556940512689692
	51934325451728388641918047049293215058642563049483
	62467221648435076201727918039944693004732956340691
	15732444386908125794514089057706229429197107928209
	55037687525678773091862540744969844508330393682126
	18336384825330154686196124348767681297534375946515
	80386287592878490201521685554828717201219257766954
	78182833757993103614740356856449095527097864797581
	16726320100436897842553539920931837441497806860984
	48403098129077791799088218795327364475675590848030
	87086987551392711854517078544161852424320693150332
	59959406895756536782107074926966537676326235447210
	69793950679652694742597709739166693763042633987085
	41052684708299085211399427365734116182760315001271
	65378607361501080857009149939512557028198746004375
	35829035317434717326932123578154982629742552737307
	94953759765105305946966067683156574377167401875275
	88902802571733229619176668713819931811048770190271
	25267680276078003013678680992525463401061632866526
	36270218540497705585629946580636237993140746255962
	24074486908231174977792365466257246923322810917141
	91430288197103288597806669760892938638285025333403
	34413065578016127815921815005561868836468420090470
	23053081172816430487623791969842487255036638784583
	11487696932154902810424020138335124462181441773470
	63783299490636259666498587618221225225512486764533
	67720186971698544312419572409913959008952310058822
	95548255300263520781532296796249481641953868218774
	76085327132285723110424803456124867697064507995236
	37774242535411291684276865538926205024910326572967
	23701913275725675285653248258265463092207058596522
	29798860272258331913126375147341994889534765745501
	18495701454879288984856827726077713721403798879715
	38298203783031473527721580348144513491373226651381
	34829543829199918180278916522431027392251122869539
	40957953066405232632538044100059654939159879593635
	29746152185502371307642255121183693803580388584903
	41698116222072977186158236678424689157993532961922
	62467957194401269043877107275048102390895523597457
	23189706772547915061505504953922979530901129967519
	86188088225875314529584099251203829009407770775672
	11306739708304724483816533873502340845647058077308
	82959174767140363198008187129011875491310547126581
	97623331044818386269515456334926366572897563400500
	42846280183517070527831839425882145521227251250327
	55121603546981200581762165212827652751691296897789
	32238195734329339946437501907836945765883352399886
	75506164965184775180738168837861091527357929701337
	62177842752192623401942399639168044983993173312731
	32924185707147349566916674687634660915035914677504
	99518671430235219628894890102423325116913619626622
	73267460800591547471830798392868535206946944540724
	76841822524674417161514036427982273348055556214818
	97142617910342598647204516893989422179826088076852
	87783646182799346313767754307809363333018982642090
	10848802521674670883215120185883543223812876952786
	71329612474782464538636993009049310363619763878039
	62184073572399794223406235393808339651327408011116
	66627891981488087797941876876144230030984490851411
	60661826293682836764744779239180335110989069790714
	85786944089552990653640447425576083659976645795096
	66024396409905389607120198219976047599490197230297
	64913982680032973156037120041377903785566085089252
	16730939319872750275468906903707539413042652315011
	94809377245048795150954100921645863754710598436791
	78639167021187492431995700641917969777599028300699
	15368713711936614952811305876380278410754449733078
	40789923115535562561142322423255033685442488917353
	44889911501440648020369068063960672322193204149535
	41503128880339536053299340368006977710650566631954
	81234880673210146739058568557934581403627822703280
	82616570773948327592232845941706525094512325230608
	22918802058777319719839450180888072429661980811197
	77158542502016545090413245809786882778948721859617
	72107838435069186155435662884062257473692284509516
	20849603980134001723930671666823555245252804609722
	53503534226472524250874054075591789781264330331690'''
    
    nums_list = list(map(int, grid.replace('\t', '').split('\n')))
    return int(str(sum(nums_list))[:size])

In [33]:
problem_13(10)

5537376230

<a id='14'></a>
## 14. Longest Collatz sequence

The following iterative sequence is defined for the set of positive integers:

$${n_{even}} â†’ \frac{n}{2}$$

$${n_{odd}} â†’ 3n + 1$$

Using the rule above and starting with 13, we generate the following sequence:

$$13 â†’ 40 â†’ 20 â†’ 10 â†’ 5 â†’ 16 â†’ 8 â†’ 4 â†’ 2 â†’ 1$$

It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

**NOTE**: Once the chain starts the terms are allowed to go above one million.

In [35]:
def problem_14(lim):
    max_num = (0, 0)
    for i in range(2, lim + 1):
        num = i
        seq = []
        while num != 1:
            seq.append(int(num))
            if num % 2 == 0:
                num /= 2
            else:
                num = 3 * num + 1
        if len(seq) > max_num[1]:
            max_num = (i, len(seq))
    return max_num[0]

In [36]:
problem_14(1000000)

837799

<a id='15'></a>
## 15. Lattice paths

Starting in the top left corner of a 2x2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.

![15](Images/15.gif)

How many such routes are there through a 20x20 grid?

In [37]:
def problem_15(size):
    routes = {'curr': {(0, 1): 1}}
    for i in range(size + size - 2):
        routes['next'] = {}
        for pos, freq in routes['curr'].items():
            for dx, dy in [(0, 1), (1, 0)]:
                step = pos[0] + dx, pos[1] + dy
                if step[0] <= size and step[1] <= size:
                    if step not in routes['next']:
                        routes['next'][step] = 1 * freq
                    else:
                        routes['next'][step] += 1 * freq
        routes['curr'] = routes['next'] 
    res = sum([freq for freq in routes['next'].values()])
    return res * 2

In [40]:
problem_15(20)

137846528820

<a id='16'></a>
## 16. Power digit sum

$2^{15} = 32768$ and the sum of its digits is 

$$3 + 2 + 7 + 6 + 8 = 26$$

What is the sum of the digits of the number $2^{1000}$?

In [5]:
def problem_16(n):
    return sum(list(map(int, [num for num in str(2**n)])))

In [6]:
problem_16(1000)

1366

<a id='17'></a>
## 17. Number letter counts

If the numbers 1 to 5 are written out in words: 

$$one, two, three, four, five$$ 

then there are 

$$3 + 3 + 5 + 4 + 4 = 19$$ 

letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

**NOTE**: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [3]:
def problem_17(lim):
    nums = {1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six',
            7: 'seven', 8: 'eight', 9: 'nine', 10: 'ten', 11: 'eleven', 
            12: 'twelve', 13: 'thirteen', 14: 'fourteen', 15: 'fifteen',
            16: 'sixteen', 17: 'seventeen', 18: 'eighteen', 19: 'nineteen',
            20: 'twenty', 30: 'thirty', 40: 'forty', 50: 'fifty', 60: 'sixty',
            70: 'seventy', 80: 'eighty', 90: 'ninety', 100: 'hundred',
            1000: 'one thousand'}
    
    count = 0
    for i in range(1, lim + 1):
        if i in nums and i != 100:
            num = nums[i]
        elif len(str(i)) == 2:
            num = nums[i // 10 * 10] + '-' + nums[i % 10]
        elif len(str(i)) == 3:
            num = nums[i // 100] + ' ' + nums[100]
            if i % 100 != 0:
                num += ' and '
                j = int(str(i)[-2:])
                if j in nums:
                    num += nums[j]
                else:
                    num += nums[j // 10 * 10] + '-' + nums[j % 10]
        count += len(num.replace('-', '').replace(' ', ''))
    return count

In [4]:
problem_17(1000)

21124

<a id='18'></a>
## 18. Maximum path sum I

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

	   3
	  7 4
	 2 4 6
	8 5 9 3
    
That is, 

$$3 + 7 + 4 + 9 = 23$$
    
Find the maximum total from top to bottom of the triangle below:

	              75
	             95 64
	            17 47 82
	           18 35 87 10
	          20 04 82 47 65
	         19 01 23 75 03 34
	        88 02 77 73 07 63 67
	       99 65 04 28 06 16 70 92
	      41 41 26 56 83 40 80 70 33
	     41 48 72 33 47 32 37 16 94 29
	    53 71 44 65 25 43 91 52 97 51 14
	   70 11 33 28 77 73 17 78 39 68 17 57
	  91 71 52 38 17 14 91 43 58 50 27 29 48
	 63 66 04 68 89 53 67 30 73 16 69 87 40 31
	04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
    
**NOTE**: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [9]:
def problem_18():
    triangle = '''75
                	95 64
                	17 47 82
                	18 35 87 10
                	20 04 82 47 65
                	19 01 23 75 03 34
                	88 02 77 73 07 63 67
                	99 65 04 28 06 16 70 92
                	41 41 26 56 83 40 80 70 33
                	41 48 72 33 47 32 37 16 94 29
                	53 71 44 65 25 43 91 52 97 51 14
                	70 11 33 28 77 73 17 78 39 68 17 57
                	91 71 52 38 17 14 91 43 58 50 27 29 48
                	63 66 04 68 89 53 67 30 73 16 69 87 40 31
                	04 62 98 27 23 09 70 98 73 93 38 53 60 04 23'''
                    
    nums_list = [list(map(int, row.split())) for row in triangle.replace('\t', ' ').split('\n')]
    total = nums_list[-1]
    for i in range(2, len(nums_list) + 1):
        total_temp = []
        for j in range(len(total) - 1):
            total_temp.append(max(total[j] + nums_list[-i][j], total[j + 1] + nums_list[-i][j]))
        total = total_temp
    return total[0]

In [10]:
problem_18()

1074

<a id='19'></a>
## 19. Counting Sundays

You are given the following information, but you may prefer to do some research for yourself.

* 1 Jan 1900 was a Monday.
* Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
	And on leap years, twenty-nine.
* A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.

How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [11]:
def problem_19(start_year, stop_year, start_dow, dow):
    counts = 0
    for year in range(start_year, stop_year + 1):
        for month in range(1, 13):
            if month in [9, 4, 6, 11]:
                days = 30
            elif month in [1, 3, 5, 7, 8, 10, 12]:
                days = 31
            elif month == 2 and (year % 4 == 0 and year % 100 != 0 or year % 400 == 0):
                days = 29
            else:
                days = 28
            start_dow = (days + start_dow) % 7
            if start_dow == 6:
                counts += 1
    return counts

In [12]:
problem_19(1901, 2000, 1, 6)

171

<a id='20'></a>
## 20. Factorial digit sum

$n!$ means 

$$n \cdot (n âˆ’ 1)\; \cdot \;... \cdot \;3 \cdot 2 \cdot 1$$

For example, 

$$10! = 10 \cdot 9\; \cdot \;... \cdot \;3 \cdot 2 \cdot 1 = 3628800$$

and the sum of the digits in the number $10!$ is 

$$3 + 6 + 2 + 8 + 8 + 0 + 0 = 27$$

Find the sum of the digits in the number $100!$

In [13]:
def problem_20(num):
    fact = 1
    for i in range(1, num + 1):
        fact *= i
    return sum(list(map(int, [num for num in str(fact)])))

In [14]:
problem_20(100)

648

<a id='21'></a>
## 21. Amicable numbers

Let $d(n)$ be defined as the sum of proper divisors of $n$ (numbers less than $n$ which divide evenly into $n$).

If $d(a) = b$ and $d(b) = a$, where $a â‰  b$, then a and b are an amicable pair and each of $a$ and $b$ are called amicable numbers.

For example, the proper divisors of 220 are 

$$1, 2, 4, 5, 10, 11, 20, 22, 44, 55, 110$$

therefore $d(220) = 284$. The proper divisors of 284 are 

$$1, 2, 4, 71, 142$$

so $d(284) = 220$.

Evaluate the sum of all the amicable numbers under 10000.

In [15]:
def problem_21(lim):
    amicable = 0
    for num in range(lim):
        da = sum([i for i in range(1, num) if num % i == 0])
        if num == da:
            continue
        db = sum([i for i in range(1, da) if da % i == 0])
        if db == num:
            amicable += num
    return amicable

In [16]:
problem_21(10000)

31626

<a id='22'></a>
## 22. Names scores

Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.
	
For example, when the list is sorted into alphabetical order, COLIN, which is worth 

$$3 + 15 + 12 + 9 + 14 = 53$$

is the 938th name in the list. So, COLIN would obtain a score of

$$938 \cdot 53 = 49714$$

What is the total of all the name scores in the file?

In [19]:
def problem_22(file):
    scores = 0
    with open(file, 'r') as file:
        names = sorted(file.read().replace('"', '').lower().split(','))
    for i, name in enumerate(names):
        value = 0
        for char in name:
            value += ord(char) - 96
        scores += value * (i + 1)
    return scores

In [22]:
problem_22('Resources/p022_names.txt')

871198282

<a id='23'></a>
## 23. Non-abundant sums

A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be $1 + 2 + 4 + 7 + 14 = 28$, which means that 28 is a perfect number.

A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.

As 12 is the smallest abundant number, $1 + 2 + 3 + 4 + 6 = 16$, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.

Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.

In [23]:
def problem_23():
    abundants = {i: i for i in range(12, 28123) if sum([num for num in range(1, int(i / 2) + 1) if i % num == 0]) > i}
    sums = 1
    for i in range(2, 28123):
        flag = True
        for abundant in abundants:
            if abundant < i:
                if (i - abundant) in abundants:
                    flag = False
                    break
            else:
                break
        if flag:
            sums += i
    return sums

In [24]:
problem_23()

4179871

<a id='24'></a>
## 24. Lexicographic permutations

A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:

$$012, 021, 102, 120, 201, 210$$

What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?

In [27]:
def problem_24(lim):
    digits = [str(i) for i in range(0, 10)]
    
    def permutation(digits):
        if len(digits) <= 1:
            yield digits
        else:
            for permute in permutation(digits[1:]):
                for i in range(len(digits)):
                    yield permute[:i] + digits[0: 1] + permute[i:]
                    
    return int(sorted([''.join(x) for x in permutation(digits)])[lim - 1])

In [28]:
problem_24(1000000)

2783915460

<a id='25'></a>
## 25. 1000-digit Fibonacci number

The Fibonacci sequence is defined by the recurrence relation:

$$F_n = F_{nâˆ’1} + F_{nâˆ’2}$$

where $F_1 = 1$ and $F_2 = 1$.

Hence the first 12 terms will be:
$$F_1 = 1$$
$$F_2 = 1$$
$$F_3 = 2$$
$$F_4 = 3$$
$$F_5 = 5$$
$$F_6 = 8$$
$$F_7 = 13$$
$$F_8 = 21$$
$$F_9 = 34$$
$$F_{10} = 55$$
$$F_{11} = 89$$
$$F_{12} = 144$$

The 12th term, $F_{12}$, is the first term to contain three digits.

What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

In [17]:
def problem_25(digits):
    fibs = [1, 2]
    fib = 2
    n = 3
    sum = 2
    while len(str(fib)) < digits:
        fib = fibs[n - 3] + fibs[n - 2]
        fibs.append(fib)
        sum += fib
        n += 1
    return n

In [18]:
problem_25(1000)

4782

<a id='26'></a>
## 26. Reciprocal cycles

A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:

$$\frac{1}{2} = 0.5$$
$$\frac{1}{3} =	0.(3)$$
$$\frac{1}{4} = 0.25$$
$$\frac{1}{5} = 0.2$$
$$\frac{1}{6} = 0.1(6)$$
$$\frac{1}{7} = 0.(142857)$$
$$\frac{1}{8} = 0.125$$
$$\frac{1}{9} = 0.(1)$$
$$\frac{1}{10} = 0.1$$

Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that $\frac{1}{7}$ has a 6-digit recurring cycle.

Find the value of $d < 1000$ for which $\frac{1}{d}$ contains the longest recurring cycle in its decimal fraction part.

In [3]:
def problem_26(lim):
    primes = [num for num in range(2, lim) if sum([i for i in range(2, round(abs(lim)**0.5) + 1) if num % i == 0]) == 0]
    for d in primes[::-1]:
        period = 1
        while 10**period % d != 1:
            period += 1
        if period == d - 1:
            return d

In [4]:
problem_26(1000)

983

<a id='27'></a>
## 27. Quadratic primes

Euler discovered the remarkable quadratic formula:

$$n^2+n+41$$

It turns out that the formula will produce 40 primes for the consecutive integer values $0â‰¤nâ‰¤39$. However, when $n=40$, $40^2+40+41=40(40+1)+41$ is divisible by 41, and certainly when $n=41$, $41^2+41+41$ is clearly divisible by 41.

The incredible formula $n^2âˆ’79n+1601$ was discovered, which produces 80 primes for the consecutive values $0â‰¤nâ‰¤79$. The product of the coefficients, âˆ’79 and 1601, is âˆ’126479.

Considering quadratics of the form:

$n^2+an+b$, where $|a|<1000$ and $|b|â‰¤1000$

where $|n|$ is the modulus/absolute value of $n$

e.g. $|11|=11$ and $|âˆ’4|=4$

Find the product of the coefficients, $a$ and $b$, for the quadratic expression that produces the maximum number of primes for consecutive values of $n$, starting with $n=0$.

In [29]:
def problem_27(a, b):
    max_primes = {'a': 0, 'b': 0, 'n': 0}
    for a in range(-1 * a, a + 1):
        for b in range(-1 * b, b + 1):
            n = 0
            while True:
                num = n**2 + a * n + b
                if len([i for i in range(2, round(abs(num)**0.5) + 1) if num % i == 0]) == 0:
                    n += 1
                else:
                    break
                if n > max_primes['n']:
                    max_primes['a'] = a
                    max_primes['b'] = b
                    max_primes['n'] = n
    return max_primes['a'] * max_primes['b']

In [30]:
problem_27(1000, 1000)

-59231

<a id='28'></a>
## 28. Number spiral diagonals

Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:

    21 22 23 24 25
    20  7  8  9 10
    19  6  1  2 11
    18  5  4  3 12
    17 16 15 14 13

It can be verified that the sum of the numbers on the diagonals is 101.

What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?

In [31]:
def problem_28(size):
    grid = [[0 for i in range(size)] for j in range(size)]
    x, y = size // 2, size // 2
    dx, dy = 0, 1
    squares = [n**2 for n in range(1, size + 1) if n % 2 != 0]
    dist = 0
    for i in range(1, size**2 + 1):
        grid[x][y] = i
        if i in squares:
            dist += 1
        new_x, new_y = x + dx, y + dy
        if max(abs(new_x - size // 2), abs(new_y - size // 2)) <= dist:
            x, y = new_x, new_y
        else:
            dx, dy = dy, -1 * dx
            x, y = x + dx, y + dy
    sums_diag = 1
    for i in range(size):
        if i != size // 2:
            sums_diag += grid[i][i] + grid[i][size - i - 1]
    return sums_diag

In [32]:
problem_28(1001)

669171001

<a id='29'></a>
## 29. Distinct powers

Consider all integer combinations of $a^b$ for $2â‰¤aâ‰¤5$ and $2â‰¤bâ‰¤5$:

$$2^2=4, 2^3=8, 2^4=16, 2^5=32$$
$$3^2=9, 3^3=27, 3^4=81, 3^5=243$$
$$4^2=16, 4^3=64, 4^4=256, 4^5=1024$$
$$5^2=25, 5^3=125, 5^4=625, 5^5=3125$$

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

$$4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125$$

How many distinct terms are in the sequence generated by $a^b$ for $2â‰¤aâ‰¤100$ and $2â‰¤bâ‰¤100$?

In [33]:
def problem_29(amin, amax, bmin, bmax):
    terms = {}
    for a in range(amin, amax + 1):
        for b in range(bmin, bmax + 1):
            num = a**b
            if num in terms:
                terms[num] += 1
            else:
                terms[num] = 1
    return len(terms)

In [34]:
problem_29(2, 100, 2, 100)

9183

<a id='30'></a>
## 30. Digit fifth powers

Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:

$$1634 = 1^4 + 6^4 + 3^4 + 4^4$$
$$8208 = 8^4 + 2^4 + 0^4 + 8^4$$
$$9474 = 9^4 + 4^4 + 7^4 + 4^4$$

As $1 = 1^4$ is not a sum it is not included.

The sum of these numbers is $1634 + 8208 + 9474 = 19316$.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.

In [1]:
def problem_30(power):
    return sum([i for i in range(2, round(9**(power + 1) / 2)) if sum([int(num)**power for num in str(i)]) == i])

In [2]:
problem_30(5)

443839

<a id='31'></a>
## 31. Coin sums

In England the currency is made up of pound, Â£, and pence, p, and there are eight coins in general circulation:

    1p, 2p, 5p, 10p, 20p, 50p, Â£1 (100p) and Â£2 (200p)

It is possible to make Â£2 in the following way:

    1Ã—Â£1 + 1Ã—50p + 2Ã—20p + 1Ã—5p + 1Ã—2p + 3Ã—1p

How many different ways can Â£2 be made using any number of coins?

In [1]:
def problem_31():
    ways = 2
    for po_1 in range(2):
        total_po_1 = po_1 * 100
        for pe_50 in range((200 - total_po_1) // 50 + 1):
            total_pe_50 = total_po_1 + pe_50 * 50
            for pe_20 in range((200 - total_pe_50) // 20 + 1):
                total_pe_20 = total_pe_50 + pe_20 * 20
                for pe_10 in range((200 - total_pe_20) // 10 + 1):
                    total_pe_10 = total_pe_20 + pe_10 * 10
                    for pe_5 in range((200 - total_pe_10) // 5 + 1):
                        total_pe_5 = total_pe_10 + pe_5 * 5
                        for pe_2 in range((200 - total_pe_5) // 2 + 1):
                            total_pe_2 = total_pe_5 + pe_2 * 2
                            for pe_1 in range(200 - total_pe_2 + 1):
                                total_pe_1 = total_pe_2 + pe_1
                                if total_pe_1 == 200:
                                    ways += 1
    return ways

In [2]:
problem_31()

73682

<a id='32'></a>
## 32. Pandigital products

We shall say that an $n$-digit number is pandigital if it makes use of all the digits 1 to $n$ exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.

The product 7254 is unusual, as the identity, 39 \cdot 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.

Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.

HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.

In [3]:
def problem_32(n):
    pandigitals = set([str(i) for i in range(1, n + 1)])
    products = {}
    for i in range(2000):
        for j in range(2000):
            s = str(i) + str(j) + str(i * j)
            if len(s) > n:
                break
            ident = set(s)
            if len(s) == n and ident == pandigitals and i * j not in products:
                products[i * j] = 1
    return sum(products.keys())

In [4]:
problem_32(9)

45228

<a id='33'></a>
## 33. Digit cancelling fractions

The fraction $\frac{49}{98}$ is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that $\frac{49}{98}$ = $\frac{4}{8}$, which is correct, is obtained by cancelling the 9s.

We shall consider fractions like, $\frac{30}{50}$ = $\frac{3}{5}$, to be trivial examples.

There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

In [5]:
def problem_33():
    prod = (1, 1)
    for i in range(10, 100):
        for j in range(10, 100):
            if i < j:
                il, ir = str(i)[0], str(i)[1]
                jl, jr = str(j)[0], str(j)[1]
                if il != ir and jl != jr and ir == jl and int(jr) != 0 and i / j == int(il) / int(jr):
                    prod = (prod[0] * int(il), prod[1] * int(jr))
    for i in range(prod[0], 0, -1):
        if prod[1] % i == 0 and prod[0] % i == 0:
            return int(prod[1] / i)

In [6]:
problem_33()

100

<a id='34'></a>
## 34. Digit factorials

145 is a curious number, as 

$$1! + 4! + 5! = 1 + 24 + 120 = 145$$

Find the sum of all numbers which are equal to the sum of the factorial of their digits.

Note: as $1! = 1$ and $2! = 2$ are not sums they are not included.

In [7]:
def problem_34():
    numbers = 0
    for i in range(3, 100000):
        facts = []
        for num in str(i):
            fact = 1
            for j in range(1, int(num) + 1):
                fact *= j
            facts.append(fact)
        if sum(facts) == i:
            numbers += sum(facts)
    return numbers

In [8]:
problem_34()

40730

<a id='35'></a>
## 35. Circular primes

The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.

There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, 97.

How many circular primes are there below one million?

In [9]:
def problem_35(lim):
    primes = {str(num): 1 for num in range(2, lim) if all(num % i for i in range(2, int(round(num**0.5 + 1))))}
    for prime in primes:
        prime_new = prime
        for i in range(len(prime)):
            prime_new = prime_new[1: len(prime_new) + 1] + prime_new[0]
            if prime_new not in primes:
                primes[prime] = 0
                break
    return len([i for i in primes.values() if i != 0])

In [10]:
problem_35(1000000)

55